vim.g.mapleader = " " -- Set the leader key to space
vim.g.maplocalleader = " " -- Set the local leader key to space
vim.g.have_nerd_font = true -- Set to true if you have a nerd font installed, false otherwise
vim.wo.number = true -- Show line numbers
vim.o.cursorline = true -- Highlight the current line
vim.o.confirm = true -- Confirm before exiting unsaved buffers
vim.o.signcolumn = "yes" -- Keep the sign column so LSP diagnostics don't shift text
vim.o.undofile = true -- Persist undo history across sessions
vim.o.ignorecase = true -- Case-insensitive search...
vim.o.smartcase = true -- ...unless the pattern has uppercase letters
vim.o.splitright = true -- Open vertical splits to the right
vim.o.splitbelow = true -- Open horizontal splits below
vim.o.scrolloff = 8 -- Keep context lines above/below the cursor
vim.o.updatetime = 250 -- Faster CursorHold (diagnostic hover, swap writes)
vim.o.clipboard = "unnamedplus" -- Yank/paste use the system clipboard
